// <auto-generated />
using System;
using Infrastructure.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.EF.Migrations
{
    [DbContext(typeof(FysioDBContext))]
    partial class FysioDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Core.Domain.Comment", b =>
                {
                    b.Property<int>("commentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("commentId"), 1L, 1);

                    b.Property<string>("content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("patientFileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("postDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("practitionerId")
                        .HasColumnType("int");

                    b.Property<bool>("visible")
                        .HasColumnType("bit");

                    b.HasKey("commentId");

                    b.HasIndex("commentId")
                        .IsUnique();

                    b.HasIndex("patientFileId");

                    b.HasIndex("practitionerId");

                    b.ToTable("comments");
                });

            modelBuilder.Entity("Core.Domain.Patient", b =>
                {
                    b.Property<int>("patientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("patientId"), 1L, 1);

                    b.Property<DateTime>("birthdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("employeeNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("patientFileId")
                        .HasColumnType("int");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("photoURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sex")
                        .HasColumnType("int");

                    b.Property<string>("studentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("patientId");

                    b.HasIndex("patientFileId")
                        .IsUnique();

                    b.HasIndex("patientId")
                        .IsUnique();

                    b.ToTable("patients");
                });

            modelBuilder.Entity("Core.Domain.PatientFile", b =>
                {
                    b.Property<int>("patientFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("patientFileId"), 1L, 1);

                    b.Property<int>("age")
                        .HasColumnType("int");

                    b.Property<DateTime>("dischargeDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("intakeByPractitionerId")
                        .HasColumnType("int");

                    b.Property<int>("patientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("registerDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("supervisedByPractitionerId")
                        .HasColumnType("int");

                    b.Property<int>("treatmentPlanId")
                        .HasColumnType("int");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("patientFileId");

                    b.HasIndex("intakeByPractitionerId");

                    b.HasIndex("patientFileId")
                        .IsUnique();

                    b.HasIndex("supervisedByPractitionerId");

                    b.HasIndex("treatmentPlanId")
                        .IsUnique();

                    b.ToTable("patientFiles");
                });

            modelBuilder.Entity("Core.Domain.Practitioner", b =>
                {
                    b.Property<int>("practitionerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("practitionerId"), 1L, 1);

                    b.Property<string>("BIGNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employeeNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("studentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("practitionerId");

                    b.HasIndex("practitionerId")
                        .IsUnique();

                    b.ToTable("practitioners");
                });

            modelBuilder.Entity("Core.Domain.Treatment", b =>
                {
                    b.Property<int>("treatmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("treatmentId"), 1L, 1);

                    b.Property<string>("location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("practitionerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("treatmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("treatmentPlanId")
                        .HasColumnType("int");

                    b.Property<string>("type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("treatmentId");

                    b.HasIndex("practitionerId");

                    b.HasIndex("treatmentId")
                        .IsUnique();

                    b.HasIndex("treatmentPlanId");

                    b.ToTable("treatments");
                });

            modelBuilder.Entity("Core.Domain.TreatmentPlan", b =>
                {
                    b.Property<int>("treatmentPlanId")
                        .HasColumnType("int");

                    b.Property<string>("complaint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("diagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("patientFileId")
                        .HasColumnType("int");

                    b.Property<int>("patientId")
                        .HasColumnType("int");

                    b.Property<int>("practitionerId")
                        .HasColumnType("int");

                    b.Property<int>("sessionDuration")
                        .HasColumnType("int");

                    b.Property<int>("weeklySessions")
                        .HasColumnType("int");

                    b.HasKey("treatmentPlanId");

                    b.HasIndex("patientId");

                    b.HasIndex("treatmentPlanId")
                        .IsUnique();

                    b.ToTable("treatmentPlans");
                });

            modelBuilder.Entity("Core.Domain.Comment", b =>
                {
                    b.HasOne("Core.Domain.PatientFile", "patientFile")
                        .WithMany("comments")
                        .HasForeignKey("patientFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Practitioner", "practitioner")
                        .WithMany()
                        .HasForeignKey("practitionerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("patientFile");

                    b.Navigation("practitioner");
                });

            modelBuilder.Entity("Core.Domain.Patient", b =>
                {
                    b.HasOne("Core.Domain.PatientFile", "patientFile")
                        .WithOne("patient")
                        .HasForeignKey("Core.Domain.Patient", "patientFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("patientFile");
                });

            modelBuilder.Entity("Core.Domain.PatientFile", b =>
                {
                    b.HasOne("Core.Domain.Practitioner", "intakeByPractitioner")
                        .WithMany("intakeByPatientFiles")
                        .HasForeignKey("intakeByPractitionerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Practitioner", "supervisedByPractitioner")
                        .WithMany("supervisedByPatientFiles")
                        .HasForeignKey("supervisedByPractitionerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.TreatmentPlan", "treatmentPlan")
                        .WithOne("pratientFile")
                        .HasForeignKey("Core.Domain.PatientFile", "treatmentPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("intakeByPractitioner");

                    b.Navigation("supervisedByPractitioner");

                    b.Navigation("treatmentPlan");
                });

            modelBuilder.Entity("Core.Domain.Treatment", b =>
                {
                    b.HasOne("Core.Domain.Practitioner", "practitioner")
                        .WithMany("treatments")
                        .HasForeignKey("practitionerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.TreatmentPlan", "treatmentPlan")
                        .WithMany("treatments")
                        .HasForeignKey("treatmentPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("practitioner");

                    b.Navigation("treatmentPlan");
                });

            modelBuilder.Entity("Core.Domain.TreatmentPlan", b =>
                {
                    b.HasOne("Core.Domain.Patient", "patient")
                        .WithMany()
                        .HasForeignKey("patientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Domain.Practitioner", "practitioner")
                        .WithMany("treatmentPlans")
                        .HasForeignKey("treatmentPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("patient");

                    b.Navigation("practitioner");
                });

            modelBuilder.Entity("Core.Domain.PatientFile", b =>
                {
                    b.Navigation("comments");

                    b.Navigation("patient");
                });

            modelBuilder.Entity("Core.Domain.Practitioner", b =>
                {
                    b.Navigation("intakeByPatientFiles");

                    b.Navigation("supervisedByPatientFiles");

                    b.Navigation("treatmentPlans");

                    b.Navigation("treatments");
                });

            modelBuilder.Entity("Core.Domain.TreatmentPlan", b =>
                {
                    b.Navigation("pratientFile");

                    b.Navigation("treatments");
                });
#pragma warning restore 612, 618
        }
    }
}
